/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mark_jnidemo_JniUtils */

#ifndef _Included_com_example_mark_jnidemo_JniUtils
#define _Included_com_example_mark_jnidemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mark_jnidemo_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mark_jnidemo_JniUtils_getStringFormC
  (JNIEnv * env, jclass clazz){
      return (*env)->NewStringUTF(env,"这里是来自33c的string");
  }

JNIEXPORT jstring JNICALL Java_com_example_mark_jnidemo_JniUtils_getStringFormC2
        (JNIEnv * env, jclass clazz){
    return (*env)->NewStringUTF(env,"这里是来自33c的string333");
}

JNIEXPORT jint JNICALL Java_com_example_mark_jnidemo_JniUtils_getIntC(JNIEnv * env,jclass clazz, jint a, jint b){
    return a+b;
}
#ifdef __cplusplus
}
#endif
#endif
